
version: '3.8'
services:
  
  server:
    stop_grace_period: 100ms
    build:
      context: ./apps/server
      dockerfile: Dockerfile.dev
    volumes:
      - ./apps/server:/usr/src/apps/server
    env_file:
      - apps/server/.env.local  
    environment:
      - PORT=5000
    expose:
      - "5000"
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.1'
          memory: 50M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    # depends_on:
    #   - db

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server
    ports:
      - "4000:4000"