dev: _deps
    docker-compose up --remove-orphans --build

dev-single: _deps
    docker-compose up --remove-orphans --build --scale server=1

restart: _deps
    docker-compose down
    just dev

_deps:
    mise install