dev: _deps
    bunx concurrently \
        "just _run-servers" \
        "just _run-web-client" \

_run-servers:
    docker-compose up --remove-orphans --build

_run-web-client:
    cd apps/web-client && bun run dev

restart: _deps
    docker-compose down
    just dev

_deps:
    mise install
    bun install -g concurrently